spring:
  profiles:
    active: prod # application-prod
  output:
    ansi:
      enabled: always

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create  # create # update

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true # false

logging:
  level:
    org.hibernate.SQL: info # debug info warn error fatal
    org.hibernate.type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true


  ## high quality img  ##
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  messages:
    basename: errors


## variable ##
file:
  path: C:/upload/

pagination:
  size: 10
